export const STATES = [
  "Andaman and Nicobar",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "NCT of Delhi",
  "Nagaland",
  "Odisha",
  "Pondicherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttrakhand",
  "West Bengal",
];

export const DISTRICTS = [
  "Agra",
  "Aligarh",
  "Ambedkarnagar",
  "Amethi",
  "Amroha",
  "Auraiya",
  "Ayodhya",
  "Azamgarh",
  "Badaun",
  "Baghpat",
  "Bahraich",
  "Ballia",
  "Balrampur",
  "Banda",
  "Barabanki",
  "Bareilly",
  "Basti",
  "Bhadohi(Sant Ravi Nagar)",
  "Bijnor",
  "Bulandshahar",
  "Chandauli",
  "Chitrakut",
  "Deoria",
  "Etah",
  "Etawah",
  "Farukhabad",
  "Fatehpur",
  "Firozabad",
  "Gautam Budh Nagar",
  "Ghaziabad",
  "Ghazipur",
  "Gonda",
  "Gorakhpur",
  "Hamirpur",
  "Hapur",
  "Hardoi",
  "Hathras",
  "Jalaun (Orai)",
  "Jaunpur",
  "Jhansi",
  "Kannuj",
  "Kanpur",
  "Kanpur Dehat",
  "Kasganj",
  "Kaushambi",
  "Khiri (Lakhimpur)",
  "Kushinagar",
  "Lakhimpur",
  "Lalitpur",
  "Lucknow",
  "Maharajganj",
  "Mahoba",
  "Mainpuri",
  "Mathura",
  "Mau(Maunathbhanjan)",
  "Meerut",
  "Mirzapur",
  "Muzaffarnagar",
  "Pillibhit",
  "Pratapgarh",
  "Prayagraj",
  "Raebarelli",
  "Rampur",
  "Saharanpur",
  "Sambhal",
  "Sant Kabir Nagar",
  "Shahjahanpur",
  "Shamli",
  "Shravasti",
  "Siddharth Nagar",
  "Sitapur",
  "Sonbhadra",
  "Unnao",
  "Varanasi",
];


export const CROPS = [
  { name: "Wheat", season: "Rabi", regions: ["Western UP", "Central UP"] },
  { name: "Rice", season: "Kharif", regions: ["Eastern UP", "Central UP"] },
  { name: "Maize", season: "Kharif", regions: ["Bundelkhand", "Eastern UP"] },
  {
    name: "Millets",
    types: ["Bajra", "Jowar", "Ragi"],
    season: "Kharif",
    regions: ["Bundelkhand", "Central UP"],
  },
  { name: "Gram", season: "Rabi", regions: ["Bundelkhand", "Western UP"] },
  { name: "Pea", season: "Rabi", regions: ["Eastern UP", "Central UP"] },
  { name: "Arhar", season: "Kharif", regions: ["Eastern UP", "Central UP"] },
  {
    name: "Moong (Green Gram)",
    season: "Kharif",
    regions: ["Western UP", "Eastern UP"],
  },
  { name: "Rajma (Kidney Beans)", season: "Rabi", regions: ["Eastern UP"] },
  { name: "Mustard", season: "Rabi", regions: ["Western UP", "Central UP"] },
  {
    name: "Groundnut",
    season: "Kharif",
    regions: ["Bundelkhand", "Eastern UP"],
  },
  {
    name: "Sesame (Til)",
    season: "Kharif",
    regions: ["Eastern UP", "Central UP"],
  },
  { name: "Linseed", season: "Rabi", regions: ["Bundelkhand"] },
  { name: "Guava", regions: ["Allahabad", "Eastern UP"] },
  { name: "Banana", regions: ["Eastern UP", "Central UP"] },
  { name: "Papaya", regions: ["Western UP", "Central UP"] },
  { name: "Onion", season: "Rabi", regions: ["Western UP", "Central UP"] },
  { name: "Tomato", season: "Kharif", regions: ["Eastern UP", "Central UP"] },
  { name: "Green Peas", season: "Rabi", regions: ["Eastern UP", "Central UP"] },
  { name: "Cabbage", season: "Rabi", regions: ["Western UP", "Central UP"] },
  { name: "Carrot", season: "Winter", regions: ["Western UP", "Central UP"] },
  { name: "Spinach", season: "Winter", regions: ["Eastern UP", "Western UP"] },
  {
    name: "Brinjal (Eggplant)",
    season: "Kharif",
    regions: ["Western UP", "Eastern UP"],
  },
  { name: "Pumpkin", season: "Kharif", regions: ["Eastern UP", "Central UP"] },
  { name: "Chili", season: "Kharif", regions: ["Eastern UP", "Central UP"] },
  { name: "Turmeric", season: "Kharif", regions: ["Bundelkhand"] },
  { name: "Garlic", season: "Rabi", regions: ["Western UP", "Eastern UP"] },
];

